spring:
  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/logging.yml
      - classpath:properties/eureka.yml
      - classpath:properties/actuator.yml
      - classpath:properties/zipkin.yml
      - classpath:properties/swagger.yml
  profiles:
    active: local

  main:
    allow-bean-definition-overriding: true
