@username="hong-gd11"
@password="password"

# @name 시스템 관리자로 로그인 API
POST {{gateway}}/auth/sign-in
Content-Type: application/json

{
  "username": {{username}},
  "password": {{password}}
}
> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

###
## 1. 전체 허브(17개) 생성
POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "서울특별시 센터",
  "address": "서울특별시 송파구 송파대로 55",
  "latitude": 37.514575,
  "longitude": 127.105392
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "경기 북부 센터",
  "address": "경기도 고양시 덕양구 권율대로 570",
  "latitude": 37.658351,
  "longitude": 126.831914
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "경기 남부 센터",
  "address": "경기도 이천시 덕평로 257-21",
  "latitude": 37.214515,
  "longitude": 127.490903
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "부산광역시 센터",
  "address": "부산 동구 중앙대로 206",
  "latitude": 35.114728,
  "longitude": 129.044343
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "대구광역시 센터",
  "address": "대구 북구 태평로 161",
  "latitude": 35.881244,
  "longitude": 128.593201
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "인천광역시 센터",
  "address": "인천 남동구 정각로 29",
  "latitude": 37.41043,
  "longitude": 126.711517
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "광주광역시 센터",
  "address": "광주 서구 내방로 111",
  "latitude": 35.15096,
  "longitude": 126.856164
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "대전광역시 센터",
  "address": "대전 서구 둔산로 100",
  "latitude": 36.350707,
  "longitude": 127.382074
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "울산광역시 센터",
  "address": "울산 남구 중앙로 201",
  "latitude": 35.538377,
  "longitude": 129.311577
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "세종특별자치시 센터",
  "address": "세종특별자치시 한누리대로 2130",
  "latitude": 36.480838,
  "longitude": 127.288169
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "강원특별자치도 센터",
  "address": "강원특별자치도 춘천시 중앙로 1",
  "latitude": 37.881317,
  "longitude": 127.72958
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "충청북도 센터",
  "address": "충북 청주시 상당구 상당로 82",
  "latitude": 36.634519,
  "longitude": 127.491706
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "충청남도 센터",
  "address": "충남 홍성군 홍북읍 충남대로 21",
  "latitude": 36.601923,
  "longitude": 126.660554
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "전북특별자치도 센터",
  "address": "전북특별자치도 전주시 완산구 효자로 225",
  "latitude": 35.821584,
  "longitude": 127.148012
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "전라남도 센터",
  "address": "전남 무안군 삼향읍 오룡길 1",
  "latitude": 34.813892,
  "longitude": 126.464501
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "경상북도 센터",
  "address": "경북 안동시 풍천면 도청대로 455",
  "latitude": 36.568061,
  "longitude": 128.720541
}

###

POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "경상남도 센터",
  "address": "경남 창원시 의창구 중앙대로 300",
  "latitude": 35.227746,
  "longitude": 128.681796
}

###

## 2. 허브 경로 전체 생성
POST {{gateway}}/hub-route/generate
Authorization: Bearer {{access_token}}

###


