management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    eureka:
      enabled: true
