spring:
  cloud:
    gateway:
      routes:
        - id: auth-app-allows-all
          uri: lb://auth-app
          predicates:
            - Path=/auth/**

        - id: user-app-authenticated
          uri: lb://user-app
          predicates:
            - Path=/user/**

        - id: company-app-authenticated
          uri: lb://company-app
          predicates:
            - Path=/company/**

        - id: hub-app-authenticated
          uri: lb://hub-app
          predicates:
            - Path=/hub/**, /hubs/**, /hub-route/**, /hub-routes/**

        - id: delivery-app-authenticated
          uri: lb://delivery-app
          predicates:
            - Path=/delivery/**, /delivery-route/**

        - id: product-app-authenticated
          uri: lb://product-app
          predicates:
            - Path=/product/**