services:
  fulflix-mysql:
    image: mysql:8.0
    container_name: fulflix_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1 --max-connections=600
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=fulflix
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=fulflix
      - MYSQL_PASSWORD=fulflix

  fulflix-zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
