spring:
  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/logging.yml
      - classpath:properties/eureka.yml
      - classpath:properties/actuator.yml
  profiles:
    active: local
