server.port: 8088

spring:
  application.name: gateway
  main.web-application-type: reactive
  cloud.gateway.discovery.locator.enabled: true
  profiles.active: local
  config:
    import:
      - classpath:properties/logging.yml
      - classpath:properties/eureka.yml
