## 생산 업체 등록 API
POST http://localhost:8088/company
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "hubId" : 2,
  "ownerId" : 4,
  "companyName" : "섬유 가공품 생산 업체",
  "companyType" : "SUPPLIER",
  "companyAddress" : "경기도 고양시"
}

###

## 수령 업체 등록 API
POST http://localhost:8088/company
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "hubId" : 4,
  "ownerId" : 5,
  "companyName" : "바구니 제작 업체",
  "companyType" : "RECEIVER",
  "companyAddress" : "부산 수영구"
}

###

## 업체 전체 조회 및 검색 API (마스터 관리자용)
GET http://localhost:8088/company/admin?query=&page=&size=&sortBy=&sortDirection=
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

## 업체 전체 조회 및 검색 API (허브 관리자, 허브 업체용)
GET http://localhost:8088/company/hub?query=&page=&size=&sortBy=&sortDirection=
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

## 업체 단일 조회 API
GET http://localhost:8088/company/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

## 업체 수정 API
PUT http://localhost:8088/company/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "companyName" : "플라스틱 가공품 생산 업체"
}

###

## 업체 삭제 API
DELETE http://localhost:8088/company/3
Content-Type: application/json
Authorization: Bearer {{access_token}}