## 업체 등록 API
POST http://localhost:8280/company
Content-Type: application/json

{
  "userId" : 1,
  "hubId" : 1,
  "companyName" : "예지컴퍼니",
  "companyType" : "SUPPLIER",
  "companyAddress" : "서울 마포구"
}

###

## 업체 전체 조회 및 검색 API
GET http://localhost:8280/company?query=컴퍼니&page=&size=&sortBy=&sortDirection=
Content-Type: application/json

###