## 배송 생성 API
POST {{gateway}}/delivery
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "orderId": 1,
  "departureHubId": 2,
  "arrivalHubId": 1,
  "deliveryAddress": "서울특별시 강남구 테헤란로 123, 45678",
  "recipient": "홍길동",
  "recipientSlackId": "hong.gildong.slack"
}

###

## 배송 수정 API
PUT {{gateway}}/delivery/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "status": "ARRIVED",
  "departureHubId": 1,
  "arrivalHubId": 2,
  "deliveryAddress": "서울특별시 강남구 테헤란로 123, 45678",
  "recipient": "홍길동",
  "recipientSlackId": "hong.gildong.slack"
}

###
