## 허브 생성 API
POST http://localhost:8088/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "서울특별시 센터",
  "address": "서울특별시 송파구 송파대로 55",
  "latitude": 37.514575,
  "longitude": 127.105392
}

###
## 허브 전체 조회 API
GET http://localhost:8088/hubs
Authorization: Bearer {{access_token}}

###
## 허브 단건 조회 API
GET http://localhost:8088/hub/1
Authorization: Bearer {{access_token}}

###

## 허브 삭제 API
DELETE http://localhost:8088/hub/1
Authorization: Bearer {{access_token}}

###

## 허브 경로 생성 API
POST http://localhost:8088/hub-route
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "departureHubId": 2,
  "arrivalHubId": 1,
  "duration": 22222
}

###

###
## 허브 경로 전체 조회 API
GET http://localhost:8088/hub-routes
Authorization: Bearer {{access_token}}

###
## 허브 경로 단건 조회 API
GET http://localhost:8088/hub-route/1
Authorization: Bearer {{access_token}}

###

## 허브 경로 수정 API
PUT http://localhost:8088/hub-route/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "departureHubId": 2,
  "arrivalHubId": 1,
  "duration": 30
}

###


## 허브 경로 삭제 API
DELETE http://localhost:8088/hub-route/1
Authorization: Bearer {{access_token}}

###
