# @name 회원가입 API
POST {{gateway}}/auth/sign-up
Content-Type: application/json

{
  "username": "hubAdmin",
  "password": "password",
  "name": "허브관리자",
  "type": "HUB_ADMIN"
}

###

# @name 로그인 API
POST {{gateway}}/auth/sign-in
Content-Type: application/json

{
  "username": "hubAdmin",
  "password": "password"
}
> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

###

## 허브 생성 API
POST {{gateway}}/hub
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "부산특별시 센터",
  "address": "서울특별시 송파구 송파대로 55",
  "latitude": 37.514575,
  "longitude": 127.105392
}

###
## 허브 전체 조회 API
GET {{gateway}}/hub
Authorization: Bearer {{access_token}}

###
## 허브 단건 조회 API
GET {{gateway}}/hub/1
Authorization: Bearer {{access_token}}

###

## 허브 삭제 API
DELETE {{gateway}}/hub/17
Authorization: Bearer {{access_token}}

###

## 허브 경로 생성 API
POST {{gateway}}/hub-route
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "departureHubId": 1,
  "arrivalHubId": 2
}

###

###
## 허브 경로 전체 조회 API
GET {{gateway}}/hub-route
Authorization: Bearer {{access_token}}

###
## 허브 경로 단건 조회 API
GET {{gateway}}/hub-route/1
Authorization: Bearer {{access_token}}

###

## 허브 경로 수정 API
PUT {{gateway}}/hub-route/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "departureHubId": 2,
  "arrivalHubId": 3,
  "duration": 30
}

###

## 허브 경로 삭제 API
DELETE {{gateway}}/hub-route/1
Authorization: Bearer {{access_token}}

###

###

## 허브 경로 전체 생성 API
POST {{gateway}}/hub-route/generate
Authorization: Bearer {{access_token}}

###

