# @name 주문 생성 API (마스터 관리자)
POST {{gateway}}/order/admin
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "supplierId": 1,
  "receiverId": 3,
  "productId": 4,
  "orderQuantity": 1
}

###

# @name 주문 생성 API (생산 업체)
POST {{gateway}}/order/supplier-company
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "receiverId": 3,
  "productId": 4,
  "orderQuantity": 1
}

###

# @name 주문 생성 API (수령 업체)
POST {{gateway}}/order/receiver-company
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "supplierId": 4,
  "productId": 4,
  "orderQuantity": 1
}

###

# @name 주문 전체 조회 및 검색 API (마스터 관리자, 허브 관리자, 생산 업체, 수령 업체)
GET {{gateway}}/order?orderQuantity=1&page=&size=30&sort=createdAt
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name 주문 단일 조회 API (마스터 관리자, 허브 관리자, 생산 업체, 수령 업체)
GET {{gateway}}/order/7
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name 주문 삭제 API (마스터 관리자, 생산 업체, 수령 업체)
DELETE {{gateway}}/order/1
Content-Type: application/json
Authorization: Bearer {{access_token}}