# @name 상품 등록 API (마스터 관리자, 허브 업체)
POST {{gateway}}/product
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "companyId": 2,
  "productName": "합성 섬유",
  "stockQuantity": 10
}

###

# @name 상품 삭제 API (마스터 관리자)
DELETE {{gateway}}/product/2
Content-Type: application/json
Authorization: Bearer {{access_token}}