## 허브 경로 한꺼번에 생성 API
POST {{gateway}}/hub-route/generate
Authorization: Bearer {{access_token}}

###

## 최단 경로 생성 API
POST {{gateway}}/shortest-path
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "startHubId": 1,
  "endHubId": 15
}

###