## 마이 페이지 API
GET {{gateway}}/user/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

## 회원 상세 조회 API
GET {{gateway}}/user/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name 회원 목록 조회 API
GET {{gateway}}/user?page=1&size=10&sort=createdAt,asc
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
