spring:
  cloud:
    gateway:
      routes:
        - id: auth-app-allows-all
          uri: lb://auth-app
          predicates:
            - Path=/auth/**

        - id: user-app-authenticated
          uri: lb://user-app
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthorizationFilter
