spring:
  cloud:
    gateway:
      routes:
        - id: auth-app-allows-all
          uri: lb://auth-app
          predicates:
            - Path=/auth/**
          filters:
            - AllowsAllRequestFilter

        - id: user-app-authenticated
          uri: lb://user-app
          predicates:
            - Path=/user/**
          filters:
            - JwtAuthorizationFilter

        - id: hub-app-authenticated
          uri: lb://hub-app
          predicates:
            - Path=/hub/**, /hubs/**, /hub-route/**, /hub-routes/**
          filters:
            - JwtAuthorizationFilter
