spring:
  jpa:
    open-in-view: false
---
spring:
  config.activate.on-profile: test
  jpa:
    database: mysql
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
