server:
  port: 8080
spring:
  application:
    name: auth-app
  profiles:
    active: local
  config:
    import:
      - classpath:properties/jwt.yml
      - classpath:properties/logging.yml
      - classpath:properties/eureka.yml
